Repository googleapis/python-dataproc-metastore, pull requests merged in 2021-08, with the labels that each got.

#59 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: api: metastore, automerge, cla: yes

#65 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, samples, api: metastore

#67 chore: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: cla: yes, api: metastore
